### ISSUE TITLE
Investigate slow server start time

### ISSUE THREAD

**Issue by jakeswenson** [paradoxical-io/cassieq#98]
I'm not sure if this is a reflection package scan issue or HazelCast. but there is a noticeable delay when starting the server. We should at least know whats causing it.

**Comment by jakeswenson** [comment]
@devshorts can you look?

**Comment by devshorts** [comment]
It's that hazelcast is waiting a period of time to do multicast discovery. this will be a lot faster if someone configure ip based discovery or uses manual or disabled cluster configuration. I was testing the container on ec2 and it starts reasonably quick. 

What we can do is set default clustering to off and have people opt into clustering since clustering requires configs such as multicast address space etc.

**Comment by devshorts** [comment]
Pretty sure that out of the box without extra configs clustering is kind of pointless since it's only scanning ip ranges inside the container so it's not going to find anything.

**Comment by jakeswenson** [comment]
:+1: awesome. Good to know. Sounds like we should change the default value?
